# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install -g yarn
    npm install -g jest-cli
    npm install -g react-native-cli
  displayName: 'install global packages'
  
- script: |
    yarn
    yarn build
    yarn test
  workingDirectory: 'msalPlugin'
  displayName: 'build and test msalPlugin'
  
- task: CopyFiles@2
  displayName: 'copy msalPlugin files to staging directory'
  inputs:
    SourceFolder: msalPlugin
    Contents: |
      **
      !*.ts
      !__tests__/**
      !node_modules/**
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: CopyFiles@2
  displayName: 'copy readme to staging directory'
  inputs:
    Contents: README.md
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish artifacts'
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'msalPlugin' 

- script: |
    cd example
    yarn
  workingDirectory: 'example'
  displayName: 'build example'