# Uncomment the next line to define a global platform for your project
platform :ios, '10'
target 'msalExample' do
    # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
    # use_frameworks!
  
    # Pods for msalExample
    pod 'MSAL', '~> 0.2'
    
  end